# -*- coding: utf-8 -*-
"""Q6_input_normalize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f7kCUuDOHfftApIrWG1t-OUn2FVdaxeV
"""

import numpy as np
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from linearRegression.linear_regression import LinearRegression
from linearRegression.metrics import *
import pandas as pd
#TODO : Write here

X, y = load_diabetes(return_X_y=True, scaled=False)
# print(X.shape, y.shape)
# plt.plot(X[:,0],y,'o')
# plt.show()
X = pd.DataFrame(X)
y = pd.Series(y)

LR = LinearRegression(fit_intercept=True)
LR.fit_sklearn_LR(X,y)
y_hat = LR.predict(X)
print('For unnormalized data, MSE error loss is: ', rmse(y_hat, y))

X = np.array(X)
y = np.array(y)
scalar = StandardScaler()
X = scalar.fit_transform(X)
y = scalar.fit_transform(y.reshape(-1,1))
y = y.reshape(-1)
LR = LinearRegression(fit_intercept=True)
LR.fit_sklearn_LR(X,y)
y_hat = LR.predict(X)
y_hat = scalar.inverse_transform(y_hat.reshape(-1,1))
print('For normalized data, MSE error loss is: ', rmse(y_hat, y))


